<template>
  <div class="home">

    <!--new account-->
   <div class="new_account">
     <b-button variant="success" @click="newAccount">newAccount</b-button>
     <div>
      {{this.newAccountInfo}}
     </div>
   </div>

    <!--import account-->
    <div class="import_account">
      <b-form @submit="onSubmit">
        <b-form-group label="key:" label-for="keyInput" description="We'll never share your key with anyone else.">
          <b-form-input id="keyInput" type="text" v-model="importKeyForm.key" required placeholder="Please enter your private key" />
        </b-form-group>
        <b-button type="submit" variant="primary">Submit</b-button>
      </b-form>
      <div>
        {{this.importAccountInfo}}
      </div>
    </div>

   <!-- transfer-->
   <!-- get utxo-->


  </div>
</template>

<script>
  import {Account} from 'nuls-js';

  export default {
    data() {
      return {
        newAccountInfo:'',

        importKeyForm: {
          key: '',
        },
        importAccountInfo:'',
      }
    },
    components: {},
    mounted() {

    },
    methods: {
      newAccount(){
        this.newAccountInfo = new Account().create(null,1,261); // Creates an account
        console.log(this.newAccountInfo)
      },

      /**
       * Import private key
       *  导入的私钥生成的地址和以前的地址不一样  The address generated by the imported private key is different from the previous address
       * @param evt
       */
      onSubmit(evt) {
        evt.preventDefault();
        this.importAccountInfo = new Account().import(null,this.importKeyForm.key); // import an account
        console.log(this.importAccountInfo);
        //alert(JSON.stringify(this.importKeyForm))
      },
    }
  }
</script>

<style lang="less">
 .home{
   width: 1024px;
   margin: 0 auto;
   .new_account{
     border: 1px solid #c1c1c1;
     margin: 10px 0 0 0;
     padding: 20px;
   }
   .import_account{
     border: 1px solid #c1c1c1;
     margin: 10px 0 0 0;
     padding: 20px;
   }
 }
</style>

