<template>
  <div class="home">

    <!--new account-->
    <div class="new_account">
      <b-button variant="success" @click="newAccount">newAccount</b-button>
      <div>
        {{this.newAccountInfo}}
      </div>
    </div>

    <!--import account-->
    <div class="import_account">
      <b-form @submit="onSubmit">
        <b-form-group label="key:" label-for="keyInput" description="We'll never share your key with anyone else.">
          <b-form-input id="keyInput" type="text" v-model="importKeyForm.key" required
                        placeholder="Please enter your private key"/>
        </b-form-group>
        <b-button type="submit" variant="primary">importAccount</b-button>
      </b-form>
      <div>
        {{this.importAccountInfo}}
      </div>
    </div>

    <!-- transfer-->
    <div class="transfer">
      <b-button type="success" variant="primary" @click="transfer">transfer</b-button>
    </div>


    <!-- get utxo-->


  </div>
</template>

<script>
  const axios = require('axios');
  import nuls from 'nuls-sdk-js';
  import utils from 'nuls-sdk-js/lib/utils/utils';
  //const nuls = require('./index');

  export default {
    data() {
      return {
        newAccountInfo: '',

        importKeyForm: {
          key: '',
        },
        importAccountInfo: '',
      }
    },
    components: {},
    mounted() {

    },
    methods: {
      newAccount() {
        let passWord = "";
        this.newAccountInfo = nuls.newAddress(passWord);
        console.log(this.newAccountInfo);
      },

      /**
       * Import private key
       *  导入的私钥生成的地址和以前的地址不一样  The address generated by the imported private key is different from the previous address
       * @param evt
       */
      onSubmit(evt) {
        //导入地址
        const key = this.importKeyForm.key;
        this.importAccountInfo = nuls.importByKey(key);
        console.log(this.importAccountInfo);

        /*evt.preventDefault();
        this.importAccountInfo = new Account().import(null,this.importKeyForm.key); // import an account
        console.log(this.importAccountInfo);*/
        //alert(JSON.stringify(this.importKeyForm))
      },

      transfer() {
        let pri = '407d5cd9b5d62ab633c52dfb45542622b06c05004a0314c312390a32b5d06234';
        let pub = '032dd7aaff8d2c3ae6597877b67f87702f44f5998b3da4459ddeb6eec8d39171c9';
        let fromAddress = 'TTaqFxuD1xc6gpixUiMVQsjMZ5fdYJ2o';
        let toAddress = 'TTakMrubBXi998CZgaYdTy2Nrqwd2ptq';
        let amount = 800000000; //8
        let remark = '测试转账开始 测试转账开始';

        //获取input utxo
        function getInputUtxo(fromAddress, amount) {
          return axios.post('http://116.62.135.185:8081/', {
            "jsonrpc": "2.0",
            "method": "getUTXOS",
            "params": [fromAddress, amount],
            "id": 1234
          })
            .then((response) => {
              return response.data.result;
            })
            .catch((error) => {
              console.log(error);
            });
        }

        //验证交易
        function valiTransaction(transactionInfo) {
          return axios.post('http://127.0.0.1:8001/api/accountledger/transaction/valiTransaction', {"txHex": transactionInfo})
            .then((response) => {
              return response;
            })
            .catch((error) => {
              console.log(error);
            });
        }

        //广播交易
        function broadcast(transactionInfo) {
          return axios.post('http://127.0.0.1:8001/api/accountledger/transaction/broadcast', {txHex: transactionInfo})
            .then((response) => {
              return response;
            })
            .catch((error) => {
              console.log(error);
            });
        }

        async function test(pri, pub, fromAddress, toAddress, amount, remark) {
          const inputUtxoInfo = await getInputUtxo(fromAddress, amount);
          let inputOwner = [];
          let totalValue = 0;
          let fee = 100000;
          //判断是否零钱过多
          if (inputUtxoInfo.length >= 6000) {
            console.log("零钱过多不能消费")
          } else {
            //计算手续费 （124 + 50  * inputs.length + 38 * outputs.length + remark.bytes.length ）/1024
            fee = Math.ceil((124 + 50 * inputUtxoInfo.length + 38 * 2 + +utils.stringToByte(remark).length) / 1024) * 100000;
          }
          //计算转账金额需要的inputUtxo
          for (let item of inputUtxoInfo) {
            totalValue = totalValue + item.value;
            inputOwner.push({owner: item.owner, na: item.value, lockTime: item.lockTime});
          }
          let outputOwner = [
            {owner: toAddress, na: amount, lockTime: 0}
          ];
          //计算多余的金额并返回
          if (totalValue - amount > 0) {
            outputOwner.push({owner: fromAddress, na: totalValue - amount - fee, lockTime: 0})
          }
          let hashOrSignature = nuls.transferTransaction(pri, pub, inputOwner, outputOwner, remark);
          //验证交易
          let valiTransactions = await valiTransaction(hashOrSignature.signature);
          console.log(valiTransactions.data);
          //广播交易
          const broadcastInfo = await broadcast(hashOrSignature.signature);
          console.log(broadcastInfo.data)
          /* //验证交易成功
           if(valiTransactions.success){
             //广播交易
             const broadcastInfo = await broadcast(hashOrSignature.signature);
             console.log(broadcastInfo.data)
           }else {
             console.log("验证交易失败")
           }*/
        }

        //测试开始
        test(pri, pub, fromAddress, toAddress, amount, remark);

      },


    }
  }
</script>

<style lang="less">
  .home {
    width: 1024px;
    margin: 0 auto;
    .new_account {
      border: 1px solid #c1c1c1;
      margin: 10px 0 0 0;
      padding: 20px;
    }
    .import_account {
      border: 1px solid #c1c1c1;
      margin: 10px 0 0 0;
      padding: 20px;
    }
    .transfer {
      border: 1px solid #c1c1c1;
      margin: 10px 0 0 0;
      padding: 20px;
    }

  }
</style>

